[package]
name = "wasm-flate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.13.0"
flate2 = "1.0.23"
wee_alloc = "0.4.5"
wasm-bindgen = "0.2.80"
console_error_panic_hook = "0.1.7"

[profile.release]
lto = true
opt-level = 'z'
